namespace WoZ.Texts;
static class City_Text
{
    // S1
    public const string C_S1_1 = "You enter a police station in chaos. Cops running from room to \nroom. The commissioner quickly greets you, and hurries you \nalong through the building. “You must be the backup we called \nfor”, he says distractedly. You don't contradict him, as this will \nmake you look like a total badass.";
    public const string C_S1_2 = "“It's a total shitshow”, he continues, “The cigarette gang \nis causing more trouble than you'd believe. We've got a standoff \nwith one of their members, by the water supply. And another \nmember keeps challenging random people to boxing matches \ndown at the beach. And don't even get me started on their boss \n“Jack the cigarette guy”.";
    public const string C_S1_3 = "“Alright you got me started. Honestly we don't know Jack all about \nthe guy — a total mystery — anyone who's come into contact with \nhim has wound up dead. They even say he's totally invulnerable \nto any attack. All we know is that he poisons his targets with a mix \nof nicotine and heavy metals.\n\n“Anyway good luck”, he pats you on the back, and rushes you out \n the other side of the building…";
    // S1: After Jack has spawned
    public const string C_S1_4 = "You storm into the building, breaking the doors in the process. In \nfront of you stands the police commissioner. “I'm glad you could \nmake it UN headquarters janitor guy”...\n\nHe takes off his burned coat and hat, revealing himself to have \nbeen a giant, 6 foot tall cigarette this whole time.\n\nYou feel the warm sensation of blood rising to your head, as you \ntry to process what's happening. “The police commissioner was \nJack the cigarette guy this whole time? What an amazing twist!”, \nyou think to yourself.\n\n“I'm afraid you're too late”, he says with a grimace, “Drop the \nlighter, UN headquarters janitor guy”. You do, and he then \nproceeds into a long monologue about his plan to poison the \nocean. ";
    public const string C_S1_5 = "“Live, Laugh and Light up in flames Jack the cigarette guy”, you \ngrab the real lighter that was taped to your back this entire time, \nand get ready for a fight.";
    // S1: Jack dies
    public const string C_S1_6 = "As Jack goes up in flames, you notice a key piece on the ground.";
    // S1: Key is picked up
    public const string C_S1_7 = "You take the key piece and contact HQ, telling them it's safe for \nthe crew to come in, and take care of the rest. \n\nYou also relay the information that thermal destruction is effective \nagainst cigarette waste.";
    // S2
    public const string C_S2_1 = "You enter a diner, and sit down by the counter. “What do ya \nwant”, the lady asks, in a monotone tone.\n";
    public const string C_S2_2 = "“One coffee, black, coming right up”, she replies.\n\n“She'll still charge you for the whole thing you know”, the guy \nsitting next to you says. “She always does this. The trick is to only \never order the coffee. But don't worry big guy, this one's on me”, \nhe says with a smile on his face.";
    public const string C_S2_3 = "“Don't mention it, it's the least I could do”, he answers, “You're the \nnew guy right? Here to help us out? Well, let me help you out first, \nby giving you a lay of the land”\n\n“You'll find this standoff north of here. I hear it's getting pretty \nserious up there”\n\n“The beach is south of here. It's usually pretty nice this time of \nyear, but ever since that gang member showed up it's been \nnothing but trouble.”";
    // S2: Second visit
    public const string C_S2_4 = "You pass by the diner again, and see the same guy, still sitting by \nthe counter. You go sit down and order another coffee.\n\n“You know, if you keep drinking all that coffee you're never gonna \nmake it to a pension";
    public const string C_S2_5 = "“No thank you”, he replies, “Got me a future partner. I'm two days \naway from retirement, my daughter's graduating from college, \nand as soon as we nail this “Jack the cigarette guy” guy, my old \nlady and I are gonna sail around the world. Just like we've always \nwanted, with just Chris and the boat”";
    public const string C_S2_6 = "He takes a picture out from his wallet and hands it to you. It \nshows a lady on a pier, with a sailboat in the background. The \nback of the boat is facing the camera, with its name — The \nLive-4-Ever — proudly displayed. \n\nEverything was made entirely of trash of course, which also \nmakes you wonder what they use to make the coffee…\n\n“Uh yes sir”, He continues, “Everythings gonna be just fine”\n\n“Oh, and I realised I totally forgot to introduce myself earlier, the \nnames Ivan, Ivan Nalive”";
    // S2: Third visit
    public const string C_S2_7 = "As you near the diner. You begin to hear loud shots and breaking \nglass. You rush around the corner, and see the entire place in \nshambles. You run in, just to see the back of the perpetrator \nrunning towards the police station, with part of his coat on fire.\n\nYou see Ivan on the ground, struggling to breathe…";
    public const string C_S2_8 = "“Uh damn. Daaamn damn”, he whispers faintly, “Friend…”";
    public const string C_S2_9 = "“I'm not gonna make it”, he says, just as the dramatic music \nbegins to kick in.";
    public const string C_S2_10 = "“No no no no, just do one thing for me”, he grabs something from \nhis pocket, “Jack… cough cough… he has a weakness… more \ncoughing… it's... it's fire, friend…” \n\nHe hands you a bunch of small pieces of metal, and an \ninstruction manual on how to assemble a lighter. Using set pieces, along with \nthe small metal container and lighter fluid you found earlier.\n\n“Just… Get… that… Jack the cigarette guy... guy...”, he \nwhispers, as he lets out a final breath";
    public const string C_S2_Talk = "Unable to believe Ivan is really dead, you kick him, just to make \nsure…\n\nIvan makes a grunting sound that kinda sounds like “Use the \nlighter to burn cigarette waste, as thermal destruction is the only \nway to take care of it.” as he opens his eyes a little. Unfortunately \nyou're already halfway through another kick…\n\nIt hits…\n\n…Yep, definitely dead…";
    // S3
    public const string C_S3_1 = "It's not long before you start hearing the commotion from the \nsstandoff. You turn the corner, and see 12 police cars surrounding \nsome sort of water treatment facility. \n\nAs you approach, you overhear a news reporter speaking. \nConveniently, just as the broadcast begins.";
    public const string C_S3_2 = "“Local Trash Island cigarette gang member breaks into a water \nstreatment facility, threatening to poison the water supply of the \nentire island!”\n\n“More than it already is, of course…” the reporter softly adds, \nslooking a little sad whilst saying it.\n\nYou wonder why anyone would take a water treatment facility as \nsa hostage, but your curiosity makes you take charge.";
    public const string C_S3_3 = "”This is the worst thing I've seen in my 40 years on the job”, he \nsays while looking over some reports. Oh, you must be the \nbackup, the commissioner called about you”, you still have no \nidea who they're talking about, “No time to talk, just get in there \nfast and take care of this”";
    // S4
    public const string C_S4_1 = "You push open the sliding doors to the building. Inside sits a large \nmonster on a throne of thousands of cigarette butts. In his hand \nhe holds lighter fuel.";
    public const string C_S4_2 = "“If you try anything funny, I'll dump my entire stockpile into the \nwater tank!\", or something along those lines, his mouth is filled \nwith still burning cigarettes, making it kinda hard to understand \nwhat he is saying.\n\nYou wonder if something already is in the water, making everyone \nact crazy in these parts. Nonetheless, you decide to take action.";
    // S4: After win
    public const string C_S4_3 = "With the monster defeated, you decide taking some of \nthe lighter fuel with you could be a good idea.";
    // S4: Leaving after collecting item
    public const string C_S4_4 = "Whilst leaving the building, the police start swarming in, confident \nafter your victory. You wonder if leaving all that lighter fuel behind \nwith the pile of flammable material was a bad idea, but you \nquickly dismiss the thought.\n\nWhile walking away, the building suddenly explodes \nbehind you, all of it happening in slow motion. \nEpic win!";
    // S5
    public const string C_S5_Beach = "Ready for a nice day on the beach, you step on something, and \nhear a crush beneath your feet. The entire beach is covered with \ncigarettes, making up almost as much of the beach as the sand. ";
    public const string C_S5_1 = "A loud voice can be heard from a distance, “Come on come all! \nAny who dares challenge me! The great champion “SULFUR THE \nBURN” will suffer! my! burn!";
    public const string C_S5_talk_1 = "Text1";
    public const string C_S5_talk_2 = "Text2";
    public const string C_S5_talk_3 = "Text3";
    // S6
    public const string C_S6_Beach = "This part of the beach is a little nicer than the previous part, but there's still cigarette butts everywhere.";
    public const string C_S6_1 = "You make your way closer to the loud announcement, barely dodging the previous \nchallenger flying towards you after being punched out of the area. \n\nThe champion lights a cigarette, \"Another one for the pile”, he \nsays with a smirk. He inhales the entire cigarette in one go, \nbefore throwing it on the ground.";
    public const string C_S6_2 = "A very dramatic flashback from your childhood plays in your mind. \nThe memory of your uncle Jack with his non-stop smoking, and \nthrowing them on the ground haunts you to this day.\n\nYou feel anger rising within you, and barely notice your feet \nmoving you towards him. ";
    public const string C_S6_3 = "“Look who we have here”, the champion says mockingly, \n“Someone seems angry, what are you gonna do, cry?”, he says \nwhile making a crying gesture with his hand. “It's not like there's \nany trash bins around anyway, and I REALLY just like to watch \nthe piles grow each time I destroy another contender”. \n\nHe smokes another cigarette, and tosses it right at you, “Here's a \nspecial one, just for you. A little taste of what's to come”";
    // S6: After win
    public const string C_S6_4 = "With a single hard punch, this so-called “champion” falls to the \ntrash, where he belongs. He apologizes and picks up the \ncigarette butt.\n\nYour reward for defeating the monster is all the civilians have to \noffer. A small metal container. It's not much, but you decide you \nshould take it with you anyway, just to be polite.";
}