namespace WoZ.Texts;
static class Mall_Text
{
    public const string M_S1_1 = "You enter a mall, made entirely of plastic. On the ground in front of \nyou, sits a man, made of plastic, with his legs crossed. He wears a\nchildren's samurai costume, and has a sheathed sword placed in \nfront of him.\n\n“Hey there stranger”, he says, in a deep — and way too serious — \ntone, “Here to slay the guardians above and claim their key piece \nfor yourself?”";
    public const string M_S1_2 = "“Your weak baby fists won't work against their hard plastic shells. \nOnly the cuts from a master crafted sword will work against them”\n\nHe unsheaths the comically large anime sword.";
    public const string M_S1_3 = "“Pretty sweet huh”, he continues, “You can have this one IF! you \ndo something for me first that is... On the second floor of this here \nbuilding, you'll find a little something I would very much like for my \ncollection.” \n \n “Now off with ya, you can't miss it, trust me”, he says with a grin on \nhis face, before closing his eyes and pretending to sleep...";
    public const string M_S1_Talk_1 = "He talks in his fake sleep, “If only… fake snoring I'd cut them \ndown… louder fake snoring when I had the chance… extremely \nloud fake snoring shredding is the only way to damage their hard \nplastic shells… fake… no wait, real drooling";
    public const string M_S1_Talk_2 = "He giddily yells back at you \"Use the sword the shred the plastic\"";
    public const string M_S1_4 = "“Hey there stran-… oh its you again, did you get the figure?”, he \nsays excitedly. A weird question, as he clearly would have heard \nyou struggling to push your cleaning cart — with the heavy figure \non top — from a mile away.";
    public const string M_S1_5 = "He pushes himself up off the ground, and takes the heavy statue \nwith surprising strength, before sprinting away like a child who just \nreceived a new video game console. Leaving the sword behind in \nhis stead…";
    public const string M_S2_1 = "You pass the food court, where a large crowd of people sits. A fine \ncloud of particles covers the area like mist. \n\nMaking your way around to get a look at the different menus — \nwhich all offer the same toy foods — the sound of people coughing \nmakes you lose your appetite.";
    public const string M_S2_2 = "The cook from one of the restaurants yells to get your attention, \n“Hey you! Come here and try our special, I call it the “Puny \nPotage”, everyone's getting it”. He hands you some potage still in \nthe non-stick pot. You take a look at the potage, which looks more \nlike wet concrete than real food, the same “mist” rises from it like \nsteam, and enters your lungs before you know it.";
    public const string M_S2_3 = "“I've made it using the finest micro plastics in all the seas”, he says \nwith an ominous smile. The thought of someone deliberately \npoisoning people with micro plastic angers you, and you decide to \ndo something about it…";
    public const string M_S3_1 = "As you make your way to the second floor, and see a life size \nBarbie doll in one of the store windows. Without a doubt in your \nmind, you know that this is the “little something” the samurai \nwanted you to get.\n\nBeside you sits an old woman sitting on a bench, coughing loudly.";
    public const string M_S3_Talk = "“Thank you for getting rid of that monster downstairs. That \nmicroplast spread everywhere, but thanks to you, it is all gone \nnow”, she says with a smile that tries to hide her sorrows.\n\nShe begins to cough again shortly after… ";
    public const string M_S4_1 = "Continuing to search the second floor for the key piece, you see \nlarge man in a trench coat and fedora up ahead, blocking the \nescalator to the 3rd floor.\n\n “Stop right there fiend!”, he yells in a nasally voice, arms crossed.\n\nThinking he might be mistaking you for someone else. You look \ndown at yourself and see that you're covered in trash, which \nexplains why he thinks you're after his funko pops...";
    public const string M_S4_2 = "“Here to steal all the funko pops from the new collection before I \ncan get to them no doubt. Well I'm here to stop you!”. He points at \nyou dramatically, and makes a weird pose.";
    public const string M_S4_3 = "With the monster finally defeated, you walk up to the escalator, just \nto find that it's not even working. Which is properly also the reason \nwhy that guy was just standing there waiting before.\n\nYou decide to just take the stairs that's right next to the escalator \ninstead.";
    public const string M_S5_1 = "You finally reach the top. It seems to be entirely dedicated to a \nlarge toy store that just opened up. Giant sale signs, and \ncommercials featuring barbie dolls, action figures, and even beach \nand bath toys."; 
    public const string M_S6_1 = "You enter the toy store proper, and are immediately met with two \ntough looking customers, looking as if they are ready for a fight.";
    public const string M_S6_2 = "The two announce themselves as Action Man and Bottle Boy. The \nformer resembles an 8 foot tall amalgamation of different action \nfigures. While the latter looked more like a small boy, made up of \nold plastic bottles, with two googly eyes on his head.";
    public const string M_S6_3 = "As you finish shredding the monsters, you see a key piece sticking \nout from inside Bottle Boy's bottle cap.";
    public const string M_S6_4 = "You contact HQ, telling them it's safe for the crew to come in and \ntake care of the rest. \n\nYou also relay the information that mechanical recycling is \neffective against plastic.";

}